name: CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install and setup uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          . .venv/bin/activate
          
      - name: Install dependencies with uv
        run: |
          . .venv/bin/activate
          uv pip install --upgrade pip
          uv pip install .[dev]
          
      - name: Start MLflow
        run: |
          . .venv/bin/activate
          mkdir -p mlruns
          mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns &
          echo "Waiting for MLflow to start..."
          for i in {1..10}; do
            if curl -s -f http://localhost:5000/health; then
              echo "MLflow is ready!"
              break
            fi
            echo "Attempt $i - MLflow not ready yet..."
            sleep 5
          done
          
      # Étape 5 : Linting avec Ruff
      - name: Lint code with Ruff
        run: |
          uv ruff check .
      # Étape 6 : Exécuter les tests avec pytest
      - name: Test with pytest
        env:
          MLFLOW_TRACKING_URI: http://localhost:5000
        run: |
          uv run pytest .
